import type { AppNotification } from "./types";

// ---------------------------------------------------------------------------
// Notifications ("Bildirimler") — mock feed.
// TODO[backend]: replace with `notifications` rows for auth.uid(),
// generated by matching jobs (new portfolio → matching searches / my searches),
// region-watch jobs (new portfolio in a watched region) and request events.
// ---------------------------------------------------------------------------

export const appNotifications: AppNotification[] = [
  {
    id: "n_001",
    kind: "match",
    title: "Arayışınıza yeni portföy eşleşti",
    body: "Bodrum deniz manzaralı villa arayışınızla yüksek uyumlu yeni bir portföy eklendi.",
    time: "12 dk önce",
    read: false,
    link: {
      to: "/dashboard/my-searches/$id",
      params: { id: "bs_001" },
      search: { tab: "matches" },
    },
  },
  {
    id: "n_002",
    kind: "portfolio",
    title: "Portföyünüz bir ağ arayışıyla eşleşti",
    body: "Yalıkavak villanız, bir profesyonelin ağ arayışıyla eşleşti.",
    time: "1 saat önce",
    read: false,
    link: { to: "/dashboard/searches/$id", params: { id: "ns_001" } },
  },
  {
    id: "n_003",
    kind: "search",
    title: "Bölgenizde yeni arayış oluşturuldu",
    body: "Bebek bölgesinde yeni bir alıcı arayışı oluşturuldu.",
    time: "3 saat önce",
    read: false,
    link: { to: "/dashboard/searches", search: { region: "Bebek" } },
  },
  {
    id: "n_004",
    kind: "region",
    title: "Takip ettiğiniz bölgede yeni portföy",
    body: "Yalıkavak bölgesinde 3 yeni luxury villa portföyü eklendi.",
    time: "8 saat önce",
    read: true,
    link: { to: "/dashboard/search", search: { region: "Yalıkavak" } },
  },
  {
    id: "n_005",
    kind: "request",
    title: "Yeni detay talebi",
    body: "Türkbükü portföyünüz için yeni bir detay talebi aldınız.",
    time: "1 gün önce",
    read: true,
    link: { to: "/dashboard/detail-requests" },
  },
  {
    id: "n_006",
    kind: "match",
    title: "Arayışınıza 2 portföy güncellendi",
    body: "Fiyat kriterlerinize uygun 2 portföy güncellendi.",
    time: "2 gün önce",
    read: true,
    link: {
      to: "/dashboard/my-searches/$id",
      params: { id: "bs_002" },
      search: { tab: "matches" },
    },
  },
];
