import type { AppNotification } from "./types";

// ---------------------------------------------------------------------------
// Notifications ("Bildirimler") — mock feed.
// TODO[backend]: replace with `notifications` rows for auth.uid(),
// generated by matching jobs (new portfolio → matching searches),
// region-watch jobs (new portfolio in a watched region) and request events.
// ---------------------------------------------------------------------------

export const appNotifications: AppNotification[] = [
  {
    id: "n_001",
    kind: "match",
    title: "Yeni yüksek uyumlu portföy",
    body: "Bebek villa arayışınızla yüksek uyumlu yeni bir portföy eklendi.",
    time: "12 dk önce",
    read: false,
    link: "/dashboard/matches",
  },
  {
    id: "n_002",
    kind: "region",
    title: "Yalıkavak'ta yeni portföyler",
    body: "Yalıkavak bölgesinde 3 yeni luxury villa portföyü eklendi.",
    time: "1 saat önce",
    read: false,
    link: "/dashboard/regions",
  },
  {
    id: "n_003",
    kind: "portfolio",
    title: "Portföyünüz eşleşti",
    body: "Portföyünüz 4 aktif arayışla eşleşti.",
    time: "3 saat önce",
    read: false,
    link: "/dashboard/matches",
  },
  {
    id: "n_004",
    kind: "search",
    title: "Arayış güncellemesi",
    body: "Bodrum deniz manzaralı villa arayışınız için 2 yeni eşleşme bulundu.",
    time: "8 saat önce",
    read: true,
    link: "/dashboard/searches",
  },
  {
    id: "n_005",
    kind: "request",
    title: "Yeni detay talebi",
    body: "Türkbükü portföyünüz için yeni bir detay talebi aldınız.",
    time: "1 gün önce",
    read: true,
    link: "/dashboard/detail-requests",
  },
  {
    id: "n_006",
    kind: "region",
    title: "Bölge talep yoğunluğu arttı",
    body: "Takip ettiğiniz Bebek bölgesinde alıcı talebi son haftada %18 arttı.",
    time: "2 gün önce",
    read: true,
    link: "/dashboard/regions",
  },
];
