/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as VUsernameRouteImport } from './routes/v.$username'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSearchRouteImport } from './routes/dashboard.search'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardFavoritesRouteImport } from './routes/dashboard.favorites'
import { Route as DashboardDetailRequestsRouteImport } from './routes/dashboard.detail-requests'
import { Route as DashboardConciergeRouteImport } from './routes/dashboard.concierge'
import { Route as DashboardAiImportRouteImport } from './routes/dashboard.ai-import'
import { Route as DashboardRegionsIndexRouteImport } from './routes/dashboard.regions.index'
import { Route as DashboardProfessionalsIndexRouteImport } from './routes/dashboard.professionals.index'
import { Route as DashboardPortfoliosIndexRouteImport } from './routes/dashboard.portfolios.index'
import { Route as DashboardBuyerSearchesIndexRouteImport } from './routes/dashboard.buyer-searches.index'
import { Route as DashboardProfessionalsIdRouteImport } from './routes/dashboard.professionals.$id'
import { Route as DashboardPortfoliosNewRouteImport } from './routes/dashboard.portfolios.new'
import { Route as DashboardBuyerSearchesNewRouteImport } from './routes/dashboard.buyer-searches.new'
import { Route as DashboardBuyerSearchesIdRouteImport } from './routes/dashboard.buyer-searches.$id'
import { Route as DashboardPortfoliosIdIndexRouteImport } from './routes/dashboard.portfolios.$id.index'
import { Route as DashboardPortfoliosIdShareRouteImport } from './routes/dashboard.portfolios.$id.share'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const VUsernameRoute = VUsernameRouteImport.update({
  id: '/v/$username',
  path: '/v/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSearchRoute = DashboardSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFavoritesRoute = DashboardFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDetailRequestsRoute = DashboardDetailRequestsRouteImport.update({
  id: '/detail-requests',
  path: '/detail-requests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConciergeRoute = DashboardConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiImportRoute = DashboardAiImportRouteImport.update({
  id: '/ai-import',
  path: '/ai-import',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRegionsIndexRoute = DashboardRegionsIndexRouteImport.update({
  id: '/regions/',
  path: '/regions/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfessionalsIndexRoute =
  DashboardProfessionalsIndexRouteImport.update({
    id: '/professionals/',
    path: '/professionals/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPortfoliosIndexRoute =
  DashboardPortfoliosIndexRouteImport.update({
    id: '/portfolios/',
    path: '/portfolios/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBuyerSearchesIndexRoute =
  DashboardBuyerSearchesIndexRouteImport.update({
    id: '/buyer-searches/',
    path: '/buyer-searches/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProfessionalsIdRoute =
  DashboardProfessionalsIdRouteImport.update({
    id: '/professionals/$id',
    path: '/professionals/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPortfoliosNewRoute = DashboardPortfoliosNewRouteImport.update({
  id: '/portfolios/new',
  path: '/portfolios/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBuyerSearchesNewRoute =
  DashboardBuyerSearchesNewRouteImport.update({
    id: '/buyer-searches/new',
    path: '/buyer-searches/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBuyerSearchesIdRoute =
  DashboardBuyerSearchesIdRouteImport.update({
    id: '/buyer-searches/$id',
    path: '/buyer-searches/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPortfoliosIdIndexRoute =
  DashboardPortfoliosIdIndexRouteImport.update({
    id: '/portfolios/$id/',
    path: '/portfolios/$id/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPortfoliosIdShareRoute =
  DashboardPortfoliosIdShareRouteImport.update({
    id: '/portfolios/$id/share',
    path: '/portfolios/$id/share',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/ai-import': typeof DashboardAiImportRoute
  '/dashboard/concierge': typeof DashboardConciergeRoute
  '/dashboard/detail-requests': typeof DashboardDetailRequestsRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/p/$slug': typeof PSlugRoute
  '/v/$username': typeof VUsernameRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/buyer-searches/$id': typeof DashboardBuyerSearchesIdRoute
  '/dashboard/buyer-searches/new': typeof DashboardBuyerSearchesNewRoute
  '/dashboard/portfolios/new': typeof DashboardPortfoliosNewRoute
  '/dashboard/professionals/$id': typeof DashboardProfessionalsIdRoute
  '/dashboard/buyer-searches/': typeof DashboardBuyerSearchesIndexRoute
  '/dashboard/portfolios/': typeof DashboardPortfoliosIndexRoute
  '/dashboard/professionals/': typeof DashboardProfessionalsIndexRoute
  '/dashboard/regions/': typeof DashboardRegionsIndexRoute
  '/dashboard/portfolios/$id/share': typeof DashboardPortfoliosIdShareRoute
  '/dashboard/portfolios/$id/': typeof DashboardPortfoliosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/ai-import': typeof DashboardAiImportRoute
  '/dashboard/concierge': typeof DashboardConciergeRoute
  '/dashboard/detail-requests': typeof DashboardDetailRequestsRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/p/$slug': typeof PSlugRoute
  '/v/$username': typeof VUsernameRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/buyer-searches/$id': typeof DashboardBuyerSearchesIdRoute
  '/dashboard/buyer-searches/new': typeof DashboardBuyerSearchesNewRoute
  '/dashboard/portfolios/new': typeof DashboardPortfoliosNewRoute
  '/dashboard/professionals/$id': typeof DashboardProfessionalsIdRoute
  '/dashboard/buyer-searches': typeof DashboardBuyerSearchesIndexRoute
  '/dashboard/portfolios': typeof DashboardPortfoliosIndexRoute
  '/dashboard/professionals': typeof DashboardProfessionalsIndexRoute
  '/dashboard/regions': typeof DashboardRegionsIndexRoute
  '/dashboard/portfolios/$id/share': typeof DashboardPortfoliosIdShareRoute
  '/dashboard/portfolios/$id': typeof DashboardPortfoliosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/ai-import': typeof DashboardAiImportRoute
  '/dashboard/concierge': typeof DashboardConciergeRoute
  '/dashboard/detail-requests': typeof DashboardDetailRequestsRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/p/$slug': typeof PSlugRoute
  '/v/$username': typeof VUsernameRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/buyer-searches/$id': typeof DashboardBuyerSearchesIdRoute
  '/dashboard/buyer-searches/new': typeof DashboardBuyerSearchesNewRoute
  '/dashboard/portfolios/new': typeof DashboardPortfoliosNewRoute
  '/dashboard/professionals/$id': typeof DashboardProfessionalsIdRoute
  '/dashboard/buyer-searches/': typeof DashboardBuyerSearchesIndexRoute
  '/dashboard/portfolios/': typeof DashboardPortfoliosIndexRoute
  '/dashboard/professionals/': typeof DashboardProfessionalsIndexRoute
  '/dashboard/regions/': typeof DashboardRegionsIndexRoute
  '/dashboard/portfolios/$id/share': typeof DashboardPortfoliosIdShareRoute
  '/dashboard/portfolios/$id/': typeof DashboardPortfoliosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/ai-import'
    | '/dashboard/concierge'
    | '/dashboard/detail-requests'
    | '/dashboard/favorites'
    | '/dashboard/profile'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/p/$slug'
    | '/v/$username'
    | '/dashboard/'
    | '/dashboard/buyer-searches/$id'
    | '/dashboard/buyer-searches/new'
    | '/dashboard/portfolios/new'
    | '/dashboard/professionals/$id'
    | '/dashboard/buyer-searches/'
    | '/dashboard/portfolios/'
    | '/dashboard/professionals/'
    | '/dashboard/regions/'
    | '/dashboard/portfolios/$id/share'
    | '/dashboard/portfolios/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/ai-import'
    | '/dashboard/concierge'
    | '/dashboard/detail-requests'
    | '/dashboard/favorites'
    | '/dashboard/profile'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/p/$slug'
    | '/v/$username'
    | '/dashboard'
    | '/dashboard/buyer-searches/$id'
    | '/dashboard/buyer-searches/new'
    | '/dashboard/portfolios/new'
    | '/dashboard/professionals/$id'
    | '/dashboard/buyer-searches'
    | '/dashboard/portfolios'
    | '/dashboard/professionals'
    | '/dashboard/regions'
    | '/dashboard/portfolios/$id/share'
    | '/dashboard/portfolios/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/ai-import'
    | '/dashboard/concierge'
    | '/dashboard/detail-requests'
    | '/dashboard/favorites'
    | '/dashboard/profile'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/p/$slug'
    | '/v/$username'
    | '/dashboard/'
    | '/dashboard/buyer-searches/$id'
    | '/dashboard/buyer-searches/new'
    | '/dashboard/portfolios/new'
    | '/dashboard/professionals/$id'
    | '/dashboard/buyer-searches/'
    | '/dashboard/portfolios/'
    | '/dashboard/professionals/'
    | '/dashboard/regions/'
    | '/dashboard/portfolios/$id/share'
    | '/dashboard/portfolios/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PSlugRoute: typeof PSlugRoute
  VUsernameRoute: typeof VUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/v/$username': {
      id: '/v/$username'
      path: '/v/$username'
      fullPath: '/v/$username'
      preLoaderRoute: typeof VUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/search': {
      id: '/dashboard/search'
      path: '/search'
      fullPath: '/dashboard/search'
      preLoaderRoute: typeof DashboardSearchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/favorites': {
      id: '/dashboard/favorites'
      path: '/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof DashboardFavoritesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/detail-requests': {
      id: '/dashboard/detail-requests'
      path: '/detail-requests'
      fullPath: '/dashboard/detail-requests'
      preLoaderRoute: typeof DashboardDetailRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/concierge': {
      id: '/dashboard/concierge'
      path: '/concierge'
      fullPath: '/dashboard/concierge'
      preLoaderRoute: typeof DashboardConciergeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-import': {
      id: '/dashboard/ai-import'
      path: '/ai-import'
      fullPath: '/dashboard/ai-import'
      preLoaderRoute: typeof DashboardAiImportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/regions/': {
      id: '/dashboard/regions/'
      path: '/regions'
      fullPath: '/dashboard/regions/'
      preLoaderRoute: typeof DashboardRegionsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/professionals/': {
      id: '/dashboard/professionals/'
      path: '/professionals'
      fullPath: '/dashboard/professionals/'
      preLoaderRoute: typeof DashboardProfessionalsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/portfolios/': {
      id: '/dashboard/portfolios/'
      path: '/portfolios'
      fullPath: '/dashboard/portfolios/'
      preLoaderRoute: typeof DashboardPortfoliosIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/buyer-searches/': {
      id: '/dashboard/buyer-searches/'
      path: '/buyer-searches'
      fullPath: '/dashboard/buyer-searches/'
      preLoaderRoute: typeof DashboardBuyerSearchesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/professionals/$id': {
      id: '/dashboard/professionals/$id'
      path: '/professionals/$id'
      fullPath: '/dashboard/professionals/$id'
      preLoaderRoute: typeof DashboardProfessionalsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/portfolios/new': {
      id: '/dashboard/portfolios/new'
      path: '/portfolios/new'
      fullPath: '/dashboard/portfolios/new'
      preLoaderRoute: typeof DashboardPortfoliosNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/buyer-searches/new': {
      id: '/dashboard/buyer-searches/new'
      path: '/buyer-searches/new'
      fullPath: '/dashboard/buyer-searches/new'
      preLoaderRoute: typeof DashboardBuyerSearchesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/buyer-searches/$id': {
      id: '/dashboard/buyer-searches/$id'
      path: '/buyer-searches/$id'
      fullPath: '/dashboard/buyer-searches/$id'
      preLoaderRoute: typeof DashboardBuyerSearchesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/portfolios/$id/': {
      id: '/dashboard/portfolios/$id/'
      path: '/portfolios/$id'
      fullPath: '/dashboard/portfolios/$id/'
      preLoaderRoute: typeof DashboardPortfoliosIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/portfolios/$id/share': {
      id: '/dashboard/portfolios/$id/share'
      path: '/portfolios/$id/share'
      fullPath: '/dashboard/portfolios/$id/share'
      preLoaderRoute: typeof DashboardPortfoliosIdShareRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAiImportRoute: typeof DashboardAiImportRoute
  DashboardConciergeRoute: typeof DashboardConciergeRoute
  DashboardDetailRequestsRoute: typeof DashboardDetailRequestsRoute
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSearchRoute: typeof DashboardSearchRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBuyerSearchesIdRoute: typeof DashboardBuyerSearchesIdRoute
  DashboardBuyerSearchesNewRoute: typeof DashboardBuyerSearchesNewRoute
  DashboardPortfoliosNewRoute: typeof DashboardPortfoliosNewRoute
  DashboardProfessionalsIdRoute: typeof DashboardProfessionalsIdRoute
  DashboardBuyerSearchesIndexRoute: typeof DashboardBuyerSearchesIndexRoute
  DashboardPortfoliosIndexRoute: typeof DashboardPortfoliosIndexRoute
  DashboardProfessionalsIndexRoute: typeof DashboardProfessionalsIndexRoute
  DashboardRegionsIndexRoute: typeof DashboardRegionsIndexRoute
  DashboardPortfoliosIdShareRoute: typeof DashboardPortfoliosIdShareRoute
  DashboardPortfoliosIdIndexRoute: typeof DashboardPortfoliosIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiImportRoute: DashboardAiImportRoute,
  DashboardConciergeRoute: DashboardConciergeRoute,
  DashboardDetailRequestsRoute: DashboardDetailRequestsRoute,
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSearchRoute: DashboardSearchRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBuyerSearchesIdRoute: DashboardBuyerSearchesIdRoute,
  DashboardBuyerSearchesNewRoute: DashboardBuyerSearchesNewRoute,
  DashboardPortfoliosNewRoute: DashboardPortfoliosNewRoute,
  DashboardProfessionalsIdRoute: DashboardProfessionalsIdRoute,
  DashboardBuyerSearchesIndexRoute: DashboardBuyerSearchesIndexRoute,
  DashboardPortfoliosIndexRoute: DashboardPortfoliosIndexRoute,
  DashboardProfessionalsIndexRoute: DashboardProfessionalsIndexRoute,
  DashboardRegionsIndexRoute: DashboardRegionsIndexRoute,
  DashboardPortfoliosIdShareRoute: DashboardPortfoliosIdShareRoute,
  DashboardPortfoliosIdIndexRoute: DashboardPortfoliosIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PSlugRoute: PSlugRoute,
  VUsernameRoute: VUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
